options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 2
    - convention: zero
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 2
  id-name-format:
    - 2
    - convention: hyphenatedbem
  leading-zero: 
    - 2
    - include: true
  mixin-name-format: 2
  mixins-before-declarations: 0
  no-extends: 2
  no-qualifying-elements: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  property-sort-order: 2
  quotes:
    - 2
    - style: double
variable-name-format: 2

files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.scss'
    - 'styles/scss/addons/**/*.scss'
    - 'styles/scss/core/**/*.scss'
    - 'styles/scss/free/**/*.scss'    
